/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalSelectCompanyRouteImport } from './routes/_portal.select-company'
import { Route as PortalBidTenderIdRouteImport } from './routes/_portal.bid.$tenderId'
import { Route as PortalMyBidsIndexRouteImport } from './routes/_portal.my-bids.index'
import { Route as PortalMyBidsBidIdRouteImport } from './routes/_portal.my-bids.$bidId'
import { Route as PortalOfficerIndexRouteImport } from './routes/_portal.officer.index'
import { Route as PortalTendersIndexRouteImport } from './routes/_portal.tenders.index'
import { Route as PortalTendersTenderIdRouteImport } from './routes/_portal.tenders.$tenderId'
import { Route as PortalOfficerBiddersIndexRouteImport } from './routes/_portal.officer.bidders.index'
import { Route as PortalOfficerBiddersBidderIdRouteImport } from './routes/_portal.officer.bidders.$bidderId'
import { Route as PortalOfficerTendersIndexRouteImport } from './routes/_portal.officer.tenders.index'
import { Route as PortalOfficerTendersTenderIdBidsRouteImport } from './routes/_portal.officer.tenders.$tenderId.bids'
import { Route as PortalOfficerTendersTenderIdRequirementsRouteImport } from './routes/_portal.officer.tenders.$tenderId.requirements'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSelectCompanyRoute = PortalSelectCompanyRouteImport.update({
  id: '/select-company',
  path: '/select-company',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBidTenderIdRoute = PortalBidTenderIdRouteImport.update({
  id: '/bid/$tenderId',
  path: '/bid/$tenderId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMyBidsIndexRoute = PortalMyBidsIndexRouteImport.update({
  id: '/my-bids/',
  path: '/my-bids/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMyBidsBidIdRoute = PortalMyBidsBidIdRouteImport.update({
  id: '/my-bids/$bidId',
  path: '/my-bids/$bidId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOfficerIndexRoute = PortalOfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTendersIndexRoute = PortalTendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTendersTenderIdRoute = PortalTendersTenderIdRouteImport.update({
  id: '/tenders/$tenderId',
  path: '/tenders/$tenderId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOfficerBiddersIndexRoute =
  PortalOfficerBiddersIndexRouteImport.update({
    id: '/officer/bidders/',
    path: '/officer/bidders/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalOfficerBiddersBidderIdRoute =
  PortalOfficerBiddersBidderIdRouteImport.update({
    id: '/officer/bidders/$bidderId',
    path: '/officer/bidders/$bidderId',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalOfficerTendersIndexRoute =
  PortalOfficerTendersIndexRouteImport.update({
    id: '/officer/tenders/',
    path: '/officer/tenders/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalOfficerTendersTenderIdBidsRoute =
  PortalOfficerTendersTenderIdBidsRouteImport.update({
    id: '/officer/tenders/$tenderId/bids',
    path: '/officer/tenders/$tenderId/bids',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalOfficerTendersTenderIdRequirementsRoute =
  PortalOfficerTendersTenderIdRequirementsRouteImport.update({
    id: '/officer/tenders/$tenderId/requirements',
    path: '/officer/tenders/$tenderId/requirements',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof PortalDashboardRoute
  '/select-company': typeof PortalSelectCompanyRoute
  '/bid/$tenderId': typeof PortalBidTenderIdRoute
  '/my-bids/$bidId': typeof PortalMyBidsBidIdRoute
  '/tenders/$tenderId': typeof PortalTendersTenderIdRoute
  '/my-bids/': typeof PortalMyBidsIndexRoute
  '/officer/': typeof PortalOfficerIndexRoute
  '/tenders/': typeof PortalTendersIndexRoute
  '/officer/bidders/$bidderId': typeof PortalOfficerBiddersBidderIdRoute
  '/officer/bidders/': typeof PortalOfficerBiddersIndexRoute
  '/officer/tenders/': typeof PortalOfficerTendersIndexRoute
  '/officer/tenders/$tenderId/bids': typeof PortalOfficerTendersTenderIdBidsRoute
  '/officer/tenders/$tenderId/requirements': typeof PortalOfficerTendersTenderIdRequirementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof PortalDashboardRoute
  '/select-company': typeof PortalSelectCompanyRoute
  '/bid/$tenderId': typeof PortalBidTenderIdRoute
  '/my-bids/$bidId': typeof PortalMyBidsBidIdRoute
  '/tenders/$tenderId': typeof PortalTendersTenderIdRoute
  '/my-bids': typeof PortalMyBidsIndexRoute
  '/officer': typeof PortalOfficerIndexRoute
  '/tenders': typeof PortalTendersIndexRoute
  '/officer/bidders/$bidderId': typeof PortalOfficerBiddersBidderIdRoute
  '/officer/bidders': typeof PortalOfficerBiddersIndexRoute
  '/officer/tenders': typeof PortalOfficerTendersIndexRoute
  '/officer/tenders/$tenderId/bids': typeof PortalOfficerTendersTenderIdBidsRoute
  '/officer/tenders/$tenderId/requirements': typeof PortalOfficerTendersTenderIdRequirementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_portal': typeof PortalRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/select-company': typeof PortalSelectCompanyRoute
  '/_portal/bid/$tenderId': typeof PortalBidTenderIdRoute
  '/_portal/my-bids/$bidId': typeof PortalMyBidsBidIdRoute
  '/_portal/tenders/$tenderId': typeof PortalTendersTenderIdRoute
  '/_portal/my-bids/': typeof PortalMyBidsIndexRoute
  '/_portal/officer/': typeof PortalOfficerIndexRoute
  '/_portal/tenders/': typeof PortalTendersIndexRoute
  '/_portal/officer/bidders/$bidderId': typeof PortalOfficerBiddersBidderIdRoute
  '/_portal/officer/bidders/': typeof PortalOfficerBiddersIndexRoute
  '/_portal/officer/tenders/': typeof PortalOfficerTendersIndexRoute
  '/_portal/officer/tenders/$tenderId/bids': typeof PortalOfficerTendersTenderIdBidsRoute
  '/_portal/officer/tenders/$tenderId/requirements': typeof PortalOfficerTendersTenderIdRequirementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/select-company'
    | '/bid/$tenderId'
    | '/my-bids/$bidId'
    | '/tenders/$tenderId'
    | '/my-bids/'
    | '/officer/'
    | '/tenders/'
    | '/officer/bidders/$bidderId'
    | '/officer/bidders/'
    | '/officer/tenders/'
    | '/officer/tenders/$tenderId/bids'
    | '/officer/tenders/$tenderId/requirements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/select-company'
    | '/bid/$tenderId'
    | '/my-bids/$bidId'
    | '/tenders/$tenderId'
    | '/my-bids'
    | '/officer'
    | '/tenders'
    | '/officer/bidders/$bidderId'
    | '/officer/bidders'
    | '/officer/tenders'
    | '/officer/tenders/$tenderId/bids'
    | '/officer/tenders/$tenderId/requirements'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_portal'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/_portal/dashboard'
    | '/_portal/select-company'
    | '/_portal/bid/$tenderId'
    | '/_portal/my-bids/$bidId'
    | '/_portal/tenders/$tenderId'
    | '/_portal/my-bids/'
    | '/_portal/officer/'
    | '/_portal/tenders/'
    | '/_portal/officer/bidders/$bidderId'
    | '/_portal/officer/bidders/'
    | '/_portal/officer/tenders/'
    | '/_portal/officer/tenders/$tenderId/bids'
    | '/_portal/officer/tenders/$tenderId/requirements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  PortalRoute: typeof PortalRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/select-company': {
      id: '/_portal/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof PortalSelectCompanyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/bid/$tenderId': {
      id: '/_portal/bid/$tenderId'
      path: '/bid/$tenderId'
      fullPath: '/bid/$tenderId'
      preLoaderRoute: typeof PortalBidTenderIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/my-bids/': {
      id: '/_portal/my-bids/'
      path: '/my-bids'
      fullPath: '/my-bids/'
      preLoaderRoute: typeof PortalMyBidsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/my-bids/$bidId': {
      id: '/_portal/my-bids/$bidId'
      path: '/my-bids/$bidId'
      fullPath: '/my-bids/$bidId'
      preLoaderRoute: typeof PortalMyBidsBidIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/officer/': {
      id: '/_portal/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof PortalOfficerIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/tenders/': {
      id: '/_portal/tenders/'
      path: '/tenders'
      fullPath: '/tenders/'
      preLoaderRoute: typeof PortalTendersIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/tenders/$tenderId': {
      id: '/_portal/tenders/$tenderId'
      path: '/tenders/$tenderId'
      fullPath: '/tenders/$tenderId'
      preLoaderRoute: typeof PortalTendersTenderIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/officer/bidders/': {
      id: '/_portal/officer/bidders/'
      path: '/officer/bidders'
      fullPath: '/officer/bidders/'
      preLoaderRoute: typeof PortalOfficerBiddersIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/officer/bidders/$bidderId': {
      id: '/_portal/officer/bidders/$bidderId'
      path: '/officer/bidders/$bidderId'
      fullPath: '/officer/bidders/$bidderId'
      preLoaderRoute: typeof PortalOfficerBiddersBidderIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/officer/tenders/': {
      id: '/_portal/officer/tenders/'
      path: '/officer/tenders'
      fullPath: '/officer/tenders/'
      preLoaderRoute: typeof PortalOfficerTendersIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/officer/tenders/$tenderId/bids': {
      id: '/_portal/officer/tenders/$tenderId/bids'
      path: '/officer/tenders/$tenderId/bids'
      fullPath: '/officer/tenders/$tenderId/bids'
      preLoaderRoute: typeof PortalOfficerTendersTenderIdBidsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/officer/tenders/$tenderId/requirements': {
      id: '/_portal/officer/tenders/$tenderId/requirements'
      path: '/officer/tenders/$tenderId/requirements'
      fullPath: '/officer/tenders/$tenderId/requirements'
      preLoaderRoute: typeof PortalOfficerTendersTenderIdRequirementsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalSelectCompanyRoute: typeof PortalSelectCompanyRoute
  PortalBidTenderIdRoute: typeof PortalBidTenderIdRoute
  PortalMyBidsBidIdRoute: typeof PortalMyBidsBidIdRoute
  PortalTendersTenderIdRoute: typeof PortalTendersTenderIdRoute
  PortalMyBidsIndexRoute: typeof PortalMyBidsIndexRoute
  PortalOfficerIndexRoute: typeof PortalOfficerIndexRoute
  PortalTendersIndexRoute: typeof PortalTendersIndexRoute
  PortalOfficerBiddersBidderIdRoute: typeof PortalOfficerBiddersBidderIdRoute
  PortalOfficerBiddersIndexRoute: typeof PortalOfficerBiddersIndexRoute
  PortalOfficerTendersIndexRoute: typeof PortalOfficerTendersIndexRoute
  PortalOfficerTendersTenderIdBidsRoute: typeof PortalOfficerTendersTenderIdBidsRoute
  PortalOfficerTendersTenderIdRequirementsRoute: typeof PortalOfficerTendersTenderIdRequirementsRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalSelectCompanyRoute: PortalSelectCompanyRoute,
  PortalBidTenderIdRoute: PortalBidTenderIdRoute,
  PortalMyBidsBidIdRoute: PortalMyBidsBidIdRoute,
  PortalTendersTenderIdRoute: PortalTendersTenderIdRoute,
  PortalMyBidsIndexRoute: PortalMyBidsIndexRoute,
  PortalOfficerIndexRoute: PortalOfficerIndexRoute,
  PortalTendersIndexRoute: PortalTendersIndexRoute,
  PortalOfficerBiddersBidderIdRoute: PortalOfficerBiddersBidderIdRoute,
  PortalOfficerBiddersIndexRoute: PortalOfficerBiddersIndexRoute,
  PortalOfficerTendersIndexRoute: PortalOfficerTendersIndexRoute,
  PortalOfficerTendersTenderIdBidsRoute: PortalOfficerTendersTenderIdBidsRoute,
  PortalOfficerTendersTenderIdRequirementsRoute:
    PortalOfficerTendersTenderIdRequirementsRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  PortalRoute: PortalRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
